/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pwrobel_darkcam1_NativeCPUBackend */

#ifndef _Included_com_pwrobel_darkcam1_NativeCPUBackend
#define _Included_com_pwrobel_darkcam1_NativeCPUBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pwrobel_darkcam1_NativeCPUBackend
 * Method:    internal_numerical_test
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_pwrobel_darkcam1_NativeCPUBackend_internal_1numerical_1test
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_pwrobel_darkcam1_NativeCPUBackend
 * Method:    process_buffer
 * Signature: ([I[IIIDDI)V
 */
JNIEXPORT void JNICALL Java_com_pwrobel_darkcam1_NativeCPUBackend_process_1buffer
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
